<html>
    <?php
    //variable to create a random number
    $lucky = rand(1, 6);
    echo 'The lucky number is: ' . $lucky;
    echo '</br>';
    $right = false;
    //while loop to continue guessing until the number is found
    while ($right == false) {
        //variable generated by rand function to provide guess
        $guess = rand(1, 6);
        echo 'The computer guessed: ' . $guess;
        echo '</br>';
        if ($guess == $lucky) {
            echo 'That is correct! Game over.';
            $right = true;
        } else {
            echo 'That is incorrect. Try again!';
            echo '</br>';
        }
    }
    ?>
</html>
