name: Build
on:
    push:
        branches:
            - develop
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: NPM Install
              run: npm ci

            - name: ESLint
              run: npm run lint

            - name: Build CSS
              run: npm run build-css

            - name: Build JavaScript
              run: npm run build-js

            - name: Discord Build Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              if: ${{ success() }}
              uses: Ilshidur/action-discord@0.3.2
              with:
                  args: '✅ Successfully built `${{ github.repository }}` on ${{ github.ref_type }}: `${{ github.ref_name }}`'

            - name: Discord Build Failure Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              if: ${{ failure() }}
              uses: Ilshidur/action-discord@0.3.2
              with:
                  args: '❗️ Build failed for `${{ github.repository }}` on ${{ github.ref_type }}: `${{ github.ref_name }}`'
