name: Check

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened

jobs:
    run_if:
        # I will only care about PRs targeting develop and main branch
        if: ${{ github.base_ref == 'main' ||  github.base_ref == 'develop' || startsWith(github.base_ref, 'release/') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: NPM Install
              run: npm ci

            - name: ESLint
              run: npm run lint

            - name: Build CSS
              run: npm run build-css

            - name: Build JavaScript
              run: npm run build-js

            - uses: kceb/pull-request-url-action@v1
              id: pr-url

            - name: Discord Build Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              if: ${{ success() }}
              uses: Ilshidur/action-discord@0.3.2
              with:
                  args: '✅ Pull Request from ${{github.event.commits[0].author.name}}) is ready for review: ${{ steps.pr-url.outputs.url }}'
