name: Check

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened

jobs:
    run_if:
        # I will only care about PRs targeting release, develop and main branch
        if: ${{ !github.event.pull_request.draft && (github.base_ref == 'main' ||  github.base_ref == 'develop' || startsWith(github.base_ref, 'release/')) }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: NPM Install
              run: npm ci

            - name: ESLint
              run: npm run lint

            - name: Build CSS
              run: npm run build-css

            - name: Build JavaScript
              run: npm run build-js

            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"

            - name: Discord Build Notification
              env:
                  DISCORD_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  DISCORD_EMBEDS: '[{"title": ${{ github.event.pull_request.title }}}]'
              if: ${{ success() }}
              uses: Ilshidur/action-discord@0.3.2
              with:
                  # [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
                  args: '✅ Pull Request from `${{ github.actor }}` is ready for review.'
