name: Check

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened

jobs:
    run_if:
        # I will only care about PRs targeting develop and main branch
        if: ${{ github.base_ref == 'main' ||  github.base_ref == 'develop' || startsWith(github.base_ref, 'release/') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: NPM Install
              run: npm ci

            - name: ESLint
              run: npm run lint

            - name: Build CSS
              run: npm run build-css

            - name: Build JavaScript
              run: npm run build-js
